### Add user
POST http://localhost:8000/user
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="image.png"
Content-Type: image/png

< ./test/kuriyan.png
--WebAppBoundary
Content-Disposition: form-data; name="user_id"
Content-Type: text/plain

kuriyan
--WebAppBoundary--

### Add user
POST http://localhost:8000/user
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="image.png"
Content-Type: image/png

< ./test/mehar.png
--WebAppBoundary
Content-Disposition: form-data; name="user_id"
Content-Type: text/plain

mehar
--WebAppBoundary--


### Get user_id from image
POST http://localhost:8000/image_to_user
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="image.png"
Content-Type: image/png

< ./test/kuriyan_vere.png
--WebAppBoundary